{
  return (ExceptionScopeInstance)resolveContextInstance(ExceptionScope.EXCEPTION_SCOPE,faultName);
}
