{
  try {
    final Cheese cheddar=new Cheese("cheddar",10);
    final DefaultFactHandle f0=(DefaultFactHandle)this.workingMemory.insert(cheddar);
    final ReteTuple tuple1=new ReteTuple(f0);
    this.node.assertTuple(tuple1,this.context,this.workingMemory);
    final Cheese brie=new Cheese("brie",10);
    final DefaultFactHandle f1=(DefaultFactHandle)this.workingMemory.insert(brie);
    assertEquals(0,this.memory.getFactHandleMemory().size());
    this.node.assertObject(f1,this.context,this.workingMemory);
    assertEquals(1,this.memory.getFactHandleMemory().size());
    this.node.retractObject(f1,this.context,this.workingMemory);
    this.node.assertObject(f1,this.context,this.workingMemory);
    assertEquals(1,this.memory.getFactHandleMemory().size());
    this.node.retractObject(f1,this.context,this.workingMemory);
    assertEquals(0,this.memory.getFactHandleMemory().size());
    assertEquals(1,this.memory.getTupleMemory().size());
    this.node.retractTuple(tuple1,this.context,this.workingMemory);
    this.node.assertTuple(tuple1,this.context,this.workingMemory);
    assertEquals(1,this.memory.getTupleMemory().size());
    this.node.retractTuple(tuple1,this.context,this.workingMemory);
    assertEquals(0,this.memory.getTupleMemory().size());
  }
 catch (  final Exception e) {
    Assert.fail("No exception should be raised in this procedure, but got: " + e.toString());
  }
}
