{
  if (testCase == null || testCase.hasErrors()) {
    throw new IllegalArgumentException("Impossible to execute test case due to existing errors: " + testCase.getErrors());
  }
  if (notifier == null) {
    notifier=EmptyNotifier.INSTANCE;
  }
  this.reteTesterHelper.addImports(testCase.getImports());
  NodeTestCaseResult result=new NodeTestCaseResult(testCase);
  for (  NodeTestDef test : testCase.getTests()) {
    notifier.fireTestStarted(test.getDescription());
    NodeTestResult testResult=run(testCase,test);
switch (testResult.result) {
case SUCCESS:
      notifier.fireTestFinished(test.getDescription());
    break;
case ERROR:
case FAILURE:
  notifier.fireTestFailure(new Failure(test.getDescription(),new AssertionError(testResult.errorMsgs)));
break;
}
result.add(testResult);
}
return result;
}
